version: '3'
services:
  nodejs:
    container_name: falcon-nodejs
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3002:3000
    volumes:
      - .:/home/falcon
    tty: true
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 8G
